
data:
  dataset_path: '../data'
  csv_data_path: './csv/train_regular.csv'
  csv_grid: 'square.csv'
  grid_augmentation: false
dataloader:
  num_workers: 6
  batch_size: 16
  shuffle: true
  prefetch_factor: 2
model:
  s1_ae_config:
    in_dim: 2
    out_dim: 1
    layer_channels: [16, 32, 64, 128]
    conv_per_layer: 1
    residual: false
    dropout_rate: 0.0
  mask_module_dim: [6, 2]
  glob_module_dims: [2, 8, 2]
  conv_block_dims: [11, 32, 64]
train:
  learning_rate: 0.001
  n_epochs: 5
  log_interval: 10
