data:
  dataset_path: '../data'
  csv_name: 'train_cloudy.csv'
  grid_augmentation: True
dataloader:
  num_workers: 6
  batch_size: 16
  shuffle: true
  prefetch_factor: 2
model:
  s1_ae_config:  # U-Net-like architecture
    in_dim: 2  # always 2 (if input={VV, VH})
    out_dim: 1
    layer_channels: [16, 32, 64]
    conv_per_layer: 1
    residual: false
    dropout_rate: 0.0
  mask_module_dim: [6, 2]  # include input dim
  glob_module_dims: [2, 8, 2]  # include input dim
  conv_block_dims: [32, 64, 128]  # exclude input dim (automatically inferred)
train:
  learning_rate: 0.001
  learning_rate_n_mult: 2  # number of times to decay lr (evenly spaced during the full training)
  learning_rate_decay: 0.2  # lr *= decay at each decay step
  n_epochs: 30
  log_interval: 20  # in iterations
  save_interval: 5  # in epochs
  interm_supervis: false  # intermediate supervision for AE
