data:
  dataset_path: '../data'
  csv_name: 'train_regular.csv'
  csv_grid_name: 'train_regular_grids.csv'
  grid_augmentation: false
dataloader:
  num_workers: 6
  batch_size: 16
  shuffle: true
  prefetch_factor: 2
model:
  name: 'hydrogen'
train:
  n_epochs: 2
  log_interval: 20  # in iterations
